'use client';
/**
 * Receipt — Structured service receipt document.
 *
 * Renders a clean, readable receipt of all service results.
 * Designed for export — date-stamped, citable, shareable.
 *
 * @module Receipt
 * @ticket T-381
 */

import type { ServiceResult, ServiceType } from './service-board.schema';

// ── Display name map ──────────────────────────────────────────

const SERVICE_LABELS: Record<ServiceType, string> = {
  'edit-abstract': 'Abstract Edit',
  'check-citations': 'Citation Check',
  spellcheck: 'Spellcheck',
  'doi-metadata': 'DOI Metadata',
  'zenodo-record': 'Zenodo Record',
};

// ── Solemn palette ────────────────────────────────────────────

const PALETTE = {
  background: '#F5F0E8',
  border: '#8B6914',
  text: '#3D2B1F',
  cardBg: '#FAF7F2',
} as const;

// ── Props ─────────────────────────────────────────────────────

interface ReceiptProps {
  results: ServiceResult[];
  workText: string;
  evaluationBand: string;
  date?: string;
}

// ── Component ─────────────────────────────────────────────────

export function Receipt({ results, workText, evaluationBand, date }: ReceiptProps) {
  const dateStr = date ?? new Date().toISOString().slice(0, 10);

  return (
    <div
      data-testid="receipt"
      style={{
        backgroundColor: PALETTE.cardBg,
        border: `1px solid ${PALETTE.border}`,
        borderRadius: '8px',
        padding: '24px',
        color: PALETTE.text,
      }}
    >
      {/* Header */}
      <div style={{ marginBottom: '20px', borderBottom: `1px solid ${PALETTE.border}`, paddingBottom: '16px' }}>
        <p
          style={{
            fontSize: '14px',
            fontWeight: 700,
            textTransform: 'uppercase',
            letterSpacing: '0.08em',
            marginBottom: '8px',
          }}
        >
          Woodchipper Service Receipt
        </p>
        <p style={{ fontSize: '13px', opacity: 0.7 }}>Date: {dateStr}</p>
        <p style={{ fontSize: '13px', opacity: 0.7 }}>Evaluation Band: {evaluationBand}</p>
      </div>

      {/* Per-service sections */}
      {results.map((result, index) => (
        <div
          key={result.serviceType}
          style={{
            marginBottom: index < results.length - 1 ? '16px' : 0,
            paddingBottom: index < results.length - 1 ? '16px' : 0,
            borderBottom: index < results.length - 1 ? `1px solid ${PALETTE.background}` : 'none',
          }}
        >
          <p
            style={{
              fontSize: '12px',
              fontWeight: 600,
              textTransform: 'uppercase',
              letterSpacing: '0.06em',
              marginBottom: '8px',
            }}
          >
            {SERVICE_LABELS[result.serviceType]}
          </p>
          <p
            style={{
              fontSize: '13px',
              lineHeight: 1.6,
              whiteSpace: 'pre-wrap',
            }}
          >
            {result.output}
          </p>
          {result.changesCount != null && (
            <p style={{ fontSize: '12px', opacity: 0.6, marginTop: '4px' }}>
              Changes applied: {result.changesCount}
            </p>
          )}
        </div>
      ))}

      {/* Footer */}
      <div
        style={{
          marginTop: '20px',
          paddingTop: '16px',
          borderTop: `1px solid ${PALETTE.border}`,
          fontSize: '11px',
          opacity: 0.5,
        }}
      >
        Generated by Woodchipper · {dateStr}
      </div>
    </div>
  );
}
